<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function report(Throwable $e){
        parent::report($e);
    }

    public function render($request, Throwable $e)
    {
        if($this->isHttpException($e)){
            $code = $e->getStatusCode();
            if($code=='404'){
                return response()->view('404');
            }else if($code=='500'){
                return response()->view('500');
            }else{
                return response()->view('generalerror');
            }
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
